### ISSUE TITLE
Example fails to compile on OS X 10.13

### ISSUE THREAD

**Issue by tyre** [ancwrd1/ipp.rs#9]
I'm trying the example from the `README` on `rustc 1.42.0-nightly (da3629b05 2019-12-29)` and see the following error on `cargo run`
```
error: linking with `cc` failed: exit code: 1
  |
  = note: "cc" "-m64" "-L"

// and then a hundred options, file paths etc. etc. finishing with:

Undefined symbols for architecture x86_64:
            "___isOSVersionAtLeast", referenced from:
                _sectransp_connect_step1 in libcurl_sys-dda71f838657d284.rlib(sectransp.o)
                _sectransp_connect_step2 in libcurl_sys-dda71f838657d284.rlib(sectransp.o)
          ld: symbol(s) not found for architecture x86_64
          clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Have you seen this before? I believe it is `futures` related (it build fine without that line). Is it possible to use this lib without `futures`?

For reference, this is the full code for `main.rs`

```rust
extern crate ipp;
use ipp::prelude::*;

pub fn main() -> Result<(), Box<dyn std::error::Error>> {
    let args: Vec<_> = std::env::args().collect();

    if args.len() < 2 {
        println!("Usage: {} uri [attrs]", args[0]);
        std::process::exit(1);
    }

    let client = IppClientBuilder::new(&args[1]).build();
    let operation = IppOperationBuilder::get_printer_attributes()
        .attributes(&args[2..])
        .build();

    let attrs = futures::executor::block_on(client.send(operation))?;

    for v in attrs.groups_of(DelimiterTag::PrinterAttributes)[0]
        .attributes()
        .values()
    {
        println!("{}: {}", v.name(), v.value());
    }

    Ok(())
}
```

and my `Cargo.toml`

```toml
[package]
name = "hello_world"
version = "0.0.0"

[dependencies]
futures = "0.3.1"
ipp = "1.0.0"
```

**Comment by dremon** [comment]
I've seen this issue on some older macOS toolchain, yes.
I think it's a problem with upstream dependency (probably curl-sys).
Here is a related issue raised already:
https://github.com/alexcrichton/curl-rust/issues/279

I will check if it's possible to add a workaround.

**Comment by tyre** [comment]
I worked around by updating to 10.14 haha so this isn't an issue for me anymore. We could close unless others have problems this since it looks like an issue with a dependency
